// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	repository "nickbar_v2/internal/repository"

	mock "github.com/stretchr/testify/mock"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

type AuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthRepository) EXPECT() *AuthRepository_Expecter {
	return &AuthRepository_Expecter{mock: &_m.Mock}
}

// ProduceToken provides a mock function with given fields: nickname
func (_m *AuthRepository) ProduceToken(nickname string) (repository.TokenPayload, error) {
	ret := _m.Called(nickname)

	if len(ret) == 0 {
		panic("no return value specified for ProduceToken")
	}

	var r0 repository.TokenPayload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (repository.TokenPayload, error)); ok {
		return rf(nickname)
	}
	if rf, ok := ret.Get(0).(func(string) repository.TokenPayload); ok {
		r0 = rf(nickname)
	} else {
		r0 = ret.Get(0).(repository.TokenPayload)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthRepository_ProduceToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProduceToken'
type AuthRepository_ProduceToken_Call struct {
	*mock.Call
}

// ProduceToken is a helper method to define mock.On call
//   - nickname string
func (_e *AuthRepository_Expecter) ProduceToken(nickname interface{}) *AuthRepository_ProduceToken_Call {
	return &AuthRepository_ProduceToken_Call{Call: _e.mock.On("ProduceToken", nickname)}
}

func (_c *AuthRepository_ProduceToken_Call) Run(run func(nickname string)) *AuthRepository_ProduceToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthRepository_ProduceToken_Call) Return(_a0 repository.TokenPayload, _a1 error) *AuthRepository_ProduceToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthRepository_ProduceToken_Call) RunAndReturn(run func(string) (repository.TokenPayload, error)) *AuthRepository_ProduceToken_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTokens provides a mock function with given fields: refrToken
func (_m *AuthRepository) RefreshTokens(refrToken string) error {
	ret := _m.Called(refrToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTokens")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(refrToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AuthRepository_RefreshTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTokens'
type AuthRepository_RefreshTokens_Call struct {
	*mock.Call
}

// RefreshTokens is a helper method to define mock.On call
//   - refrToken string
func (_e *AuthRepository_Expecter) RefreshTokens(refrToken interface{}) *AuthRepository_RefreshTokens_Call {
	return &AuthRepository_RefreshTokens_Call{Call: _e.mock.On("RefreshTokens", refrToken)}
}

func (_c *AuthRepository_RefreshTokens_Call) Run(run func(refrToken string)) *AuthRepository_RefreshTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthRepository_RefreshTokens_Call) Return(_a0 error) *AuthRepository_RefreshTokens_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AuthRepository_RefreshTokens_Call) RunAndReturn(run func(string) error) *AuthRepository_RefreshTokens_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateToken provides a mock function with given fields: accToken
func (_m *AuthRepository) ValidateToken(accToken string) (bool, string, error) {
	ret := _m.Called(accToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateToken")
	}

	var r0 bool
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (bool, string, error)); ok {
		return rf(accToken)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(accToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(accToken)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(accToken)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// AuthRepository_ValidateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateToken'
type AuthRepository_ValidateToken_Call struct {
	*mock.Call
}

// ValidateToken is a helper method to define mock.On call
//   - accToken string
func (_e *AuthRepository_Expecter) ValidateToken(accToken interface{}) *AuthRepository_ValidateToken_Call {
	return &AuthRepository_ValidateToken_Call{Call: _e.mock.On("ValidateToken", accToken)}
}

func (_c *AuthRepository_ValidateToken_Call) Run(run func(accToken string)) *AuthRepository_ValidateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *AuthRepository_ValidateToken_Call) Return(_a0 bool, _a1 string, _a2 error) *AuthRepository_ValidateToken_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *AuthRepository_ValidateToken_Call) RunAndReturn(run func(string) (bool, string, error)) *AuthRepository_ValidateToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
