// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// CocktailRepository is an autogenerated mock type for the CocktailRepository type
type CocktailRepository struct {
	mock.Mock
}

type CocktailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CocktailRepository) EXPECT() *CocktailRepository_Expecter {
	return &CocktailRepository_Expecter{mock: &_m.Mock}
}

// CreateCocktail provides a mock function with given fields: ctx, cocktail
func (_m *CocktailRepository) CreateCocktail(ctx context.Context, cocktail models.Cocktail) (models.Cocktail, error) {
	ret := _m.Called(ctx, cocktail)

	if len(ret) == 0 {
		panic("no return value specified for CreateCocktail")
	}

	var r0 models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Cocktail) (models.Cocktail, error)); ok {
		return rf(ctx, cocktail)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Cocktail) models.Cocktail); ok {
		r0 = rf(ctx, cocktail)
	} else {
		r0 = ret.Get(0).(models.Cocktail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Cocktail) error); ok {
		r1 = rf(ctx, cocktail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_CreateCocktail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCocktail'
type CocktailRepository_CreateCocktail_Call struct {
	*mock.Call
}

// CreateCocktail is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktail models.Cocktail
func (_e *CocktailRepository_Expecter) CreateCocktail(ctx interface{}, cocktail interface{}) *CocktailRepository_CreateCocktail_Call {
	return &CocktailRepository_CreateCocktail_Call{Call: _e.mock.On("CreateCocktail", ctx, cocktail)}
}

func (_c *CocktailRepository_CreateCocktail_Call) Run(run func(ctx context.Context, cocktail models.Cocktail)) *CocktailRepository_CreateCocktail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Cocktail))
	})
	return _c
}

func (_c *CocktailRepository_CreateCocktail_Call) Return(_a0 models.Cocktail, _a1 error) *CocktailRepository_CreateCocktail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_CreateCocktail_Call) RunAndReturn(run func(context.Context, models.Cocktail) (models.Cocktail, error)) *CocktailRepository_CreateCocktail_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCocktail provides a mock function with given fields: ctx, id
func (_m *CocktailRepository) DeleteCocktail(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCocktail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CocktailRepository_DeleteCocktail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCocktail'
type CocktailRepository_DeleteCocktail_Call struct {
	*mock.Call
}

// DeleteCocktail is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CocktailRepository_Expecter) DeleteCocktail(ctx interface{}, id interface{}) *CocktailRepository_DeleteCocktail_Call {
	return &CocktailRepository_DeleteCocktail_Call{Call: _e.mock.On("DeleteCocktail", ctx, id)}
}

func (_c *CocktailRepository_DeleteCocktail_Call) Run(run func(ctx context.Context, id string)) *CocktailRepository_DeleteCocktail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CocktailRepository_DeleteCocktail_Call) Return(_a0 error) *CocktailRepository_DeleteCocktail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CocktailRepository_DeleteCocktail_Call) RunAndReturn(run func(context.Context, string) error) *CocktailRepository_DeleteCocktail_Call {
	_c.Call.Return(run)
	return _c
}

// GetCocktailByID provides a mock function with given fields: ctx, id
func (_m *CocktailRepository) GetCocktailByID(ctx context.Context, id string) (models.Cocktail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetCocktailByID")
	}

	var r0 models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Cocktail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Cocktail); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.Cocktail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_GetCocktailByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCocktailByID'
type CocktailRepository_GetCocktailByID_Call struct {
	*mock.Call
}

// GetCocktailByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *CocktailRepository_Expecter) GetCocktailByID(ctx interface{}, id interface{}) *CocktailRepository_GetCocktailByID_Call {
	return &CocktailRepository_GetCocktailByID_Call{Call: _e.mock.On("GetCocktailByID", ctx, id)}
}

func (_c *CocktailRepository_GetCocktailByID_Call) Run(run func(ctx context.Context, id string)) *CocktailRepository_GetCocktailByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CocktailRepository_GetCocktailByID_Call) Return(_a0 models.Cocktail, _a1 error) *CocktailRepository_GetCocktailByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_GetCocktailByID_Call) RunAndReturn(run func(context.Context, string) (models.Cocktail, error)) *CocktailRepository_GetCocktailByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCocktails provides a mock function with given fields: ctx, isApproved, usedId
func (_m *CocktailRepository) GetCocktails(ctx context.Context, isApproved bool, usedId string) ([]models.Cocktail, error) {
	ret := _m.Called(ctx, isApproved, usedId)

	if len(ret) == 0 {
		panic("no return value specified for GetCocktails")
	}

	var r0 []models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) ([]models.Cocktail, error)); ok {
		return rf(ctx, isApproved, usedId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool, string) []models.Cocktail); ok {
		r0 = rf(ctx, isApproved, usedId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Cocktail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool, string) error); ok {
		r1 = rf(ctx, isApproved, usedId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_GetCocktails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCocktails'
type CocktailRepository_GetCocktails_Call struct {
	*mock.Call
}

// GetCocktails is a helper method to define mock.On call
//   - ctx context.Context
//   - isApproved bool
//   - usedId string
func (_e *CocktailRepository_Expecter) GetCocktails(ctx interface{}, isApproved interface{}, usedId interface{}) *CocktailRepository_GetCocktails_Call {
	return &CocktailRepository_GetCocktails_Call{Call: _e.mock.On("GetCocktails", ctx, isApproved, usedId)}
}

func (_c *CocktailRepository_GetCocktails_Call) Run(run func(ctx context.Context, isApproved bool, usedId string)) *CocktailRepository_GetCocktails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bool), args[2].(string))
	})
	return _c
}

func (_c *CocktailRepository_GetCocktails_Call) Return(_a0 []models.Cocktail, _a1 error) *CocktailRepository_GetCocktails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_GetCocktails_Call) RunAndReturn(run func(context.Context, bool, string) ([]models.Cocktail, error)) *CocktailRepository_GetCocktails_Call {
	_c.Call.Return(run)
	return _c
}

// GetCocktailsByIngredients provides a mock function with given fields: ctx, ingredientNames
func (_m *CocktailRepository) GetCocktailsByIngredients(ctx context.Context, ingredientNames []string) ([]models.Cocktail, error) {
	ret := _m.Called(ctx, ingredientNames)

	if len(ret) == 0 {
		panic("no return value specified for GetCocktailsByIngredients")
	}

	var r0 []models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]models.Cocktail, error)); ok {
		return rf(ctx, ingredientNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []models.Cocktail); ok {
		r0 = rf(ctx, ingredientNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Cocktail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ingredientNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_GetCocktailsByIngredients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCocktailsByIngredients'
type CocktailRepository_GetCocktailsByIngredients_Call struct {
	*mock.Call
}

// GetCocktailsByIngredients is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientNames []string
func (_e *CocktailRepository_Expecter) GetCocktailsByIngredients(ctx interface{}, ingredientNames interface{}) *CocktailRepository_GetCocktailsByIngredients_Call {
	return &CocktailRepository_GetCocktailsByIngredients_Call{Call: _e.mock.On("GetCocktailsByIngredients", ctx, ingredientNames)}
}

func (_c *CocktailRepository_GetCocktailsByIngredients_Call) Run(run func(ctx context.Context, ingredientNames []string)) *CocktailRepository_GetCocktailsByIngredients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CocktailRepository_GetCocktailsByIngredients_Call) Return(_a0 []models.Cocktail, _a1 error) *CocktailRepository_GetCocktailsByIngredients_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_GetCocktailsByIngredients_Call) RunAndReturn(run func(context.Context, []string) ([]models.Cocktail, error)) *CocktailRepository_GetCocktailsByIngredients_Call {
	_c.Call.Return(run)
	return _c
}

// GetCocktailsByName provides a mock function with given fields: ctx, name
func (_m *CocktailRepository) GetCocktailsByName(ctx context.Context, name string) ([]models.Cocktail, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetCocktailsByName")
	}

	var r0 []models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Cocktail, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Cocktail); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Cocktail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_GetCocktailsByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCocktailsByName'
type CocktailRepository_GetCocktailsByName_Call struct {
	*mock.Call
}

// GetCocktailsByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CocktailRepository_Expecter) GetCocktailsByName(ctx interface{}, name interface{}) *CocktailRepository_GetCocktailsByName_Call {
	return &CocktailRepository_GetCocktailsByName_Call{Call: _e.mock.On("GetCocktailsByName", ctx, name)}
}

func (_c *CocktailRepository_GetCocktailsByName_Call) Run(run func(ctx context.Context, name string)) *CocktailRepository_GetCocktailsByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CocktailRepository_GetCocktailsByName_Call) Return(_a0 []models.Cocktail, _a1 error) *CocktailRepository_GetCocktailsByName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_GetCocktailsByName_Call) RunAndReturn(run func(context.Context, string) ([]models.Cocktail, error)) *CocktailRepository_GetCocktailsByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetCocktailsByTags provides a mock function with given fields: ctx, tagNames
func (_m *CocktailRepository) GetCocktailsByTags(ctx context.Context, tagNames []string) ([]models.Cocktail, error) {
	ret := _m.Called(ctx, tagNames)

	if len(ret) == 0 {
		panic("no return value specified for GetCocktailsByTags")
	}

	var r0 []models.Cocktail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]models.Cocktail, error)); ok {
		return rf(ctx, tagNames)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []models.Cocktail); ok {
		r0 = rf(ctx, tagNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Cocktail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, tagNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_GetCocktailsByTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCocktailsByTags'
type CocktailRepository_GetCocktailsByTags_Call struct {
	*mock.Call
}

// GetCocktailsByTags is a helper method to define mock.On call
//   - ctx context.Context
//   - tagNames []string
func (_e *CocktailRepository_Expecter) GetCocktailsByTags(ctx interface{}, tagNames interface{}) *CocktailRepository_GetCocktailsByTags_Call {
	return &CocktailRepository_GetCocktailsByTags_Call{Call: _e.mock.On("GetCocktailsByTags", ctx, tagNames)}
}

func (_c *CocktailRepository_GetCocktailsByTags_Call) Run(run func(ctx context.Context, tagNames []string)) *CocktailRepository_GetCocktailsByTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *CocktailRepository_GetCocktailsByTags_Call) Return(_a0 []models.Cocktail, _a1 error) *CocktailRepository_GetCocktailsByTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_GetCocktailsByTags_Call) RunAndReturn(run func(context.Context, []string) ([]models.Cocktail, error)) *CocktailRepository_GetCocktailsByTags_Call {
	_c.Call.Return(run)
	return _c
}

// IsCocktailExistAndApproved provides a mock function with given fields: ctx, name
func (_m *CocktailRepository) IsCocktailExistAndApproved(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsCocktailExistAndApproved")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CocktailRepository_IsCocktailExistAndApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCocktailExistAndApproved'
type CocktailRepository_IsCocktailExistAndApproved_Call struct {
	*mock.Call
}

// IsCocktailExistAndApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CocktailRepository_Expecter) IsCocktailExistAndApproved(ctx interface{}, name interface{}) *CocktailRepository_IsCocktailExistAndApproved_Call {
	return &CocktailRepository_IsCocktailExistAndApproved_Call{Call: _e.mock.On("IsCocktailExistAndApproved", ctx, name)}
}

func (_c *CocktailRepository_IsCocktailExistAndApproved_Call) Run(run func(ctx context.Context, name string)) *CocktailRepository_IsCocktailExistAndApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CocktailRepository_IsCocktailExistAndApproved_Call) Return(_a0 bool, _a1 error) *CocktailRepository_IsCocktailExistAndApproved_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CocktailRepository_IsCocktailExistAndApproved_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *CocktailRepository_IsCocktailExistAndApproved_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCocktail provides a mock function with given fields: ctx, cocktail
func (_m *CocktailRepository) UpdateCocktail(ctx context.Context, cocktail models.Cocktail) error {
	ret := _m.Called(ctx, cocktail)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCocktail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Cocktail) error); ok {
		r0 = rf(ctx, cocktail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CocktailRepository_UpdateCocktail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCocktail'
type CocktailRepository_UpdateCocktail_Call struct {
	*mock.Call
}

// UpdateCocktail is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktail models.Cocktail
func (_e *CocktailRepository_Expecter) UpdateCocktail(ctx interface{}, cocktail interface{}) *CocktailRepository_UpdateCocktail_Call {
	return &CocktailRepository_UpdateCocktail_Call{Call: _e.mock.On("UpdateCocktail", ctx, cocktail)}
}

func (_c *CocktailRepository_UpdateCocktail_Call) Run(run func(ctx context.Context, cocktail models.Cocktail)) *CocktailRepository_UpdateCocktail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Cocktail))
	})
	return _c
}

func (_c *CocktailRepository_UpdateCocktail_Call) Return(_a0 error) *CocktailRepository_UpdateCocktail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CocktailRepository_UpdateCocktail_Call) RunAndReturn(run func(context.Context, models.Cocktail) error) *CocktailRepository_UpdateCocktail_Call {
	_c.Call.Return(run)
	return _c
}

// NewCocktailRepository creates a new instance of CocktailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCocktailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CocktailRepository {
	mock := &CocktailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
