// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// CsIngredientNomRepository is an autogenerated mock type for the CsIngredientNomRepository type
type CsIngredientNomRepository struct {
	mock.Mock
}

type CsIngredientNomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CsIngredientNomRepository) EXPECT() *CsIngredientNomRepository_Expecter {
	return &CsIngredientNomRepository_Expecter{mock: &_m.Mock}
}

// CreateIngredientNom provides a mock function with given fields: ctx, nomenclature
func (_m *CsIngredientNomRepository) CreateIngredientNom(ctx context.Context, nomenclature models.IngredientNomenclature) (models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, nomenclature)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredientNom")
	}

	var r0 models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)); ok {
		return rf(ctx, nomenclature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) models.IngredientNomenclature); ok {
		r0 = rf(ctx, nomenclature)
	} else {
		r0 = ret.Get(0).(models.IngredientNomenclature)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.IngredientNomenclature) error); ok {
		r1 = rf(ctx, nomenclature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CsIngredientNomRepository_CreateIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredientNom'
type CsIngredientNomRepository_CreateIngredientNom_Call struct {
	*mock.Call
}

// CreateIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
//   - nomenclature models.IngredientNomenclature
func (_e *CsIngredientNomRepository_Expecter) CreateIngredientNom(ctx interface{}, nomenclature interface{}) *CsIngredientNomRepository_CreateIngredientNom_Call {
	return &CsIngredientNomRepository_CreateIngredientNom_Call{Call: _e.mock.On("CreateIngredientNom", ctx, nomenclature)}
}

func (_c *CsIngredientNomRepository_CreateIngredientNom_Call) Run(run func(ctx context.Context, nomenclature models.IngredientNomenclature)) *CsIngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.IngredientNomenclature))
	})
	return _c
}

func (_c *CsIngredientNomRepository_CreateIngredientNom_Call) Return(_a0 models.IngredientNomenclature, _a1 error) *CsIngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CsIngredientNomRepository_CreateIngredientNom_Call) RunAndReturn(run func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)) *CsIngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// IsIngredientNomExistAndApproved provides a mock function with given fields: ctx, name
func (_m *CsIngredientNomRepository) IsIngredientNomExistAndApproved(ctx context.Context, name string) (bool, models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsIngredientNomExistAndApproved")
	}

	var r0 bool
	var r1 models.IngredientNomenclature
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, models.IngredientNomenclature, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) models.IngredientNomenclature); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(models.IngredientNomenclature)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIngredientNomExistAndApproved'
type CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call struct {
	*mock.Call
}

// IsIngredientNomExistAndApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CsIngredientNomRepository_Expecter) IsIngredientNomExistAndApproved(ctx interface{}, name interface{}) *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call {
	return &CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call{Call: _e.mock.On("IsIngredientNomExistAndApproved", ctx, name)}
}

func (_c *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call) Run(run func(ctx context.Context, name string)) *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call) Return(_a0 bool, _a1 models.IngredientNomenclature, _a2 error) *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call) RunAndReturn(run func(context.Context, string) (bool, models.IngredientNomenclature, error)) *CsIngredientNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Return(run)
	return _c
}

// NewCsIngredientNomRepository creates a new instance of CsIngredientNomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCsIngredientNomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CsIngredientNomRepository {
	mock := &CsIngredientNomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
