// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// CsIngredientRepository is an autogenerated mock type for the CsIngredientRepository type
type CsIngredientRepository struct {
	mock.Mock
}

type CsIngredientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CsIngredientRepository) EXPECT() *CsIngredientRepository_Expecter {
	return &CsIngredientRepository_Expecter{mock: &_m.Mock}
}

// CreateIngredient provides a mock function with given fields: ctx, cocktailID, ingredient
func (_m *CsIngredientRepository) CreateIngredient(ctx context.Context, cocktailID string, ingredient models.Ingredient) (models.Ingredient, error) {
	ret := _m.Called(ctx, cocktailID, ingredient)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredient")
	}

	var r0 models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Ingredient) (models.Ingredient, error)); ok {
		return rf(ctx, cocktailID, ingredient)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Ingredient) models.Ingredient); ok {
		r0 = rf(ctx, cocktailID, ingredient)
	} else {
		r0 = ret.Get(0).(models.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Ingredient) error); ok {
		r1 = rf(ctx, cocktailID, ingredient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CsIngredientRepository_CreateIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredient'
type CsIngredientRepository_CreateIngredient_Call struct {
	*mock.Call
}

// CreateIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailID string
//   - ingredient models.Ingredient
func (_e *CsIngredientRepository_Expecter) CreateIngredient(ctx interface{}, cocktailID interface{}, ingredient interface{}) *CsIngredientRepository_CreateIngredient_Call {
	return &CsIngredientRepository_CreateIngredient_Call{Call: _e.mock.On("CreateIngredient", ctx, cocktailID, ingredient)}
}

func (_c *CsIngredientRepository_CreateIngredient_Call) Run(run func(ctx context.Context, cocktailID string, ingredient models.Ingredient)) *CsIngredientRepository_CreateIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Ingredient))
	})
	return _c
}

func (_c *CsIngredientRepository_CreateIngredient_Call) Return(_a0 models.Ingredient, _a1 error) *CsIngredientRepository_CreateIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CsIngredientRepository_CreateIngredient_Call) RunAndReturn(run func(context.Context, string, models.Ingredient) (models.Ingredient, error)) *CsIngredientRepository_CreateIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngredientsByCocktailID provides a mock function with given fields: ctx, cocktailId
func (_m *CsIngredientRepository) GetIngredientsByCocktailID(ctx context.Context, cocktailId string) ([]models.Ingredient, error) {
	ret := _m.Called(ctx, cocktailId)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredientsByCocktailID")
	}

	var r0 []models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Ingredient, error)); ok {
		return rf(ctx, cocktailId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Ingredient); ok {
		r0 = rf(ctx, cocktailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cocktailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CsIngredientRepository_GetIngredientsByCocktailID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredientsByCocktailID'
type CsIngredientRepository_GetIngredientsByCocktailID_Call struct {
	*mock.Call
}

// GetIngredientsByCocktailID is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
func (_e *CsIngredientRepository_Expecter) GetIngredientsByCocktailID(ctx interface{}, cocktailId interface{}) *CsIngredientRepository_GetIngredientsByCocktailID_Call {
	return &CsIngredientRepository_GetIngredientsByCocktailID_Call{Call: _e.mock.On("GetIngredientsByCocktailID", ctx, cocktailId)}
}

func (_c *CsIngredientRepository_GetIngredientsByCocktailID_Call) Run(run func(ctx context.Context, cocktailId string)) *CsIngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CsIngredientRepository_GetIngredientsByCocktailID_Call) Return(_a0 []models.Ingredient, _a1 error) *CsIngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CsIngredientRepository_GetIngredientsByCocktailID_Call) RunAndReturn(run func(context.Context, string) ([]models.Ingredient, error)) *CsIngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Return(run)
	return _c
}

// NewCsIngredientRepository creates a new instance of CsIngredientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCsIngredientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CsIngredientRepository {
	mock := &CsIngredientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
