// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// CsTagRepository is an autogenerated mock type for the CsTagRepository type
type CsTagRepository struct {
	mock.Mock
}

type CsTagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *CsTagRepository) EXPECT() *CsTagRepository_Expecter {
	return &CsTagRepository_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function with given fields: ctx, tag
func (_m *CsTagRepository) CreateTag(ctx context.Context, tag models.Tag) (models.Tag, error) {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Tag) (models.Tag, error)); ok {
		return rf(ctx, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Tag) models.Tag); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Get(0).(models.Tag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Tag) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CsTagRepository_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type CsTagRepository_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag models.Tag
func (_e *CsTagRepository_Expecter) CreateTag(ctx interface{}, tag interface{}) *CsTagRepository_CreateTag_Call {
	return &CsTagRepository_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, tag)}
}

func (_c *CsTagRepository_CreateTag_Call) Run(run func(ctx context.Context, tag models.Tag)) *CsTagRepository_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Tag))
	})
	return _c
}

func (_c *CsTagRepository_CreateTag_Call) Return(_a0 models.Tag, _a1 error) *CsTagRepository_CreateTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CsTagRepository_CreateTag_Call) RunAndReturn(run func(context.Context, models.Tag) (models.Tag, error)) *CsTagRepository_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByCocktailID provides a mock function with given fields: ctx, cocktailId
func (_m *CsTagRepository) GetTagsByCocktailID(ctx context.Context, cocktailId string) ([]models.Tag, error) {
	ret := _m.Called(ctx, cocktailId)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByCocktailID")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Tag, error)); ok {
		return rf(ctx, cocktailId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Tag); ok {
		r0 = rf(ctx, cocktailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cocktailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CsTagRepository_GetTagsByCocktailID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByCocktailID'
type CsTagRepository_GetTagsByCocktailID_Call struct {
	*mock.Call
}

// GetTagsByCocktailID is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
func (_e *CsTagRepository_Expecter) GetTagsByCocktailID(ctx interface{}, cocktailId interface{}) *CsTagRepository_GetTagsByCocktailID_Call {
	return &CsTagRepository_GetTagsByCocktailID_Call{Call: _e.mock.On("GetTagsByCocktailID", ctx, cocktailId)}
}

func (_c *CsTagRepository_GetTagsByCocktailID_Call) Run(run func(ctx context.Context, cocktailId string)) *CsTagRepository_GetTagsByCocktailID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CsTagRepository_GetTagsByCocktailID_Call) Return(_a0 []models.Tag, _a1 error) *CsTagRepository_GetTagsByCocktailID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CsTagRepository_GetTagsByCocktailID_Call) RunAndReturn(run func(context.Context, string) ([]models.Tag, error)) *CsTagRepository_GetTagsByCocktailID_Call {
	_c.Call.Return(run)
	return _c
}

// IsTagExistAndApproved provides a mock function with given fields: ctx, name
func (_m *CsTagRepository) IsTagExistAndApproved(ctx context.Context, name string) (bool, models.Tag, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsTagExistAndApproved")
	}

	var r0 bool
	var r1 models.Tag
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, models.Tag, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) models.Tag); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(models.Tag)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// CsTagRepository_IsTagExistAndApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTagExistAndApproved'
type CsTagRepository_IsTagExistAndApproved_Call struct {
	*mock.Call
}

// IsTagExistAndApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *CsTagRepository_Expecter) IsTagExistAndApproved(ctx interface{}, name interface{}) *CsTagRepository_IsTagExistAndApproved_Call {
	return &CsTagRepository_IsTagExistAndApproved_Call{Call: _e.mock.On("IsTagExistAndApproved", ctx, name)}
}

func (_c *CsTagRepository_IsTagExistAndApproved_Call) Run(run func(ctx context.Context, name string)) *CsTagRepository_IsTagExistAndApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *CsTagRepository_IsTagExistAndApproved_Call) Return(_a0 bool, _a1 models.Tag, _a2 error) *CsTagRepository_IsTagExistAndApproved_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *CsTagRepository_IsTagExistAndApproved_Call) RunAndReturn(run func(context.Context, string) (bool, models.Tag, error)) *CsTagRepository_IsTagExistAndApproved_Call {
	_c.Call.Return(run)
	return _c
}

// NewCsTagRepository creates a new instance of CsTagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCsTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *CsTagRepository {
	mock := &CsTagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
