// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// IngredientRepository is an autogenerated mock type for the IngredientRepository type
type IngredientRepository struct {
	mock.Mock
}

type IngredientRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IngredientRepository) EXPECT() *IngredientRepository_Expecter {
	return &IngredientRepository_Expecter{mock: &_m.Mock}
}

// CreateIngredient provides a mock function with given fields: ctx, cocktailID, ingredient
func (_m *IngredientRepository) CreateIngredient(ctx context.Context, cocktailID string, ingredient models.Ingredient) (models.Ingredient, error) {
	ret := _m.Called(ctx, cocktailID, ingredient)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredient")
	}

	var r0 models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Ingredient) (models.Ingredient, error)); ok {
		return rf(ctx, cocktailID, ingredient)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.Ingredient) models.Ingredient); ok {
		r0 = rf(ctx, cocktailID, ingredient)
	} else {
		r0 = ret.Get(0).(models.Ingredient)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.Ingredient) error); ok {
		r1 = rf(ctx, cocktailID, ingredient)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientRepository_CreateIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredient'
type IngredientRepository_CreateIngredient_Call struct {
	*mock.Call
}

// CreateIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailID string
//   - ingredient models.Ingredient
func (_e *IngredientRepository_Expecter) CreateIngredient(ctx interface{}, cocktailID interface{}, ingredient interface{}) *IngredientRepository_CreateIngredient_Call {
	return &IngredientRepository_CreateIngredient_Call{Call: _e.mock.On("CreateIngredient", ctx, cocktailID, ingredient)}
}

func (_c *IngredientRepository_CreateIngredient_Call) Run(run func(ctx context.Context, cocktailID string, ingredient models.Ingredient)) *IngredientRepository_CreateIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.Ingredient))
	})
	return _c
}

func (_c *IngredientRepository_CreateIngredient_Call) Return(_a0 models.Ingredient, _a1 error) *IngredientRepository_CreateIngredient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientRepository_CreateIngredient_Call) RunAndReturn(run func(context.Context, string, models.Ingredient) (models.Ingredient, error)) *IngredientRepository_CreateIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIngredient provides a mock function with given fields: ctx, ingredientID, cocktailID, userID
func (_m *IngredientRepository) DeleteIngredient(ctx context.Context, ingredientID string, cocktailID string, userID string) error {
	ret := _m.Called(ctx, ingredientID, cocktailID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, ingredientID, cocktailID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngredientRepository_DeleteIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngredient'
type IngredientRepository_DeleteIngredient_Call struct {
	*mock.Call
}

// DeleteIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredientID string
//   - cocktailID string
//   - userID string
func (_e *IngredientRepository_Expecter) DeleteIngredient(ctx interface{}, ingredientID interface{}, cocktailID interface{}, userID interface{}) *IngredientRepository_DeleteIngredient_Call {
	return &IngredientRepository_DeleteIngredient_Call{Call: _e.mock.On("DeleteIngredient", ctx, ingredientID, cocktailID, userID)}
}

func (_c *IngredientRepository_DeleteIngredient_Call) Run(run func(ctx context.Context, ingredientID string, cocktailID string, userID string)) *IngredientRepository_DeleteIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *IngredientRepository_DeleteIngredient_Call) Return(_a0 error) *IngredientRepository_DeleteIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngredientRepository_DeleteIngredient_Call) RunAndReturn(run func(context.Context, string, string, string) error) *IngredientRepository_DeleteIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngredientsByCocktailID provides a mock function with given fields: ctx, cocktailId
func (_m *IngredientRepository) GetIngredientsByCocktailID(ctx context.Context, cocktailId string) ([]models.Ingredient, error) {
	ret := _m.Called(ctx, cocktailId)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredientsByCocktailID")
	}

	var r0 []models.Ingredient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Ingredient, error)); ok {
		return rf(ctx, cocktailId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Ingredient); ok {
		r0 = rf(ctx, cocktailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Ingredient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cocktailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientRepository_GetIngredientsByCocktailID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredientsByCocktailID'
type IngredientRepository_GetIngredientsByCocktailID_Call struct {
	*mock.Call
}

// GetIngredientsByCocktailID is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
func (_e *IngredientRepository_Expecter) GetIngredientsByCocktailID(ctx interface{}, cocktailId interface{}) *IngredientRepository_GetIngredientsByCocktailID_Call {
	return &IngredientRepository_GetIngredientsByCocktailID_Call{Call: _e.mock.On("GetIngredientsByCocktailID", ctx, cocktailId)}
}

func (_c *IngredientRepository_GetIngredientsByCocktailID_Call) Run(run func(ctx context.Context, cocktailId string)) *IngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IngredientRepository_GetIngredientsByCocktailID_Call) Return(_a0 []models.Ingredient, _a1 error) *IngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientRepository_GetIngredientsByCocktailID_Call) RunAndReturn(run func(context.Context, string) ([]models.Ingredient, error)) *IngredientRepository_GetIngredientsByCocktailID_Call {
	_c.Call.Return(run)
	return _c
}

// InsertIngredient provides a mock function with given fields: ctx, ingredient, cocktailID
func (_m *IngredientRepository) InsertIngredient(ctx context.Context, ingredient models.Ingredient, cocktailID string) error {
	ret := _m.Called(ctx, ingredient, cocktailID)

	if len(ret) == 0 {
		panic("no return value specified for InsertIngredient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Ingredient, string) error); ok {
		r0 = rf(ctx, ingredient, cocktailID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngredientRepository_InsertIngredient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertIngredient'
type IngredientRepository_InsertIngredient_Call struct {
	*mock.Call
}

// InsertIngredient is a helper method to define mock.On call
//   - ctx context.Context
//   - ingredient models.Ingredient
//   - cocktailID string
func (_e *IngredientRepository_Expecter) InsertIngredient(ctx interface{}, ingredient interface{}, cocktailID interface{}) *IngredientRepository_InsertIngredient_Call {
	return &IngredientRepository_InsertIngredient_Call{Call: _e.mock.On("InsertIngredient", ctx, ingredient, cocktailID)}
}

func (_c *IngredientRepository_InsertIngredient_Call) Run(run func(ctx context.Context, ingredient models.Ingredient, cocktailID string)) *IngredientRepository_InsertIngredient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Ingredient), args[2].(string))
	})
	return _c
}

func (_c *IngredientRepository_InsertIngredient_Call) Return(_a0 error) *IngredientRepository_InsertIngredient_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngredientRepository_InsertIngredient_Call) RunAndReturn(run func(context.Context, models.Ingredient, string) error) *IngredientRepository_InsertIngredient_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngredientRepository creates a new instance of IngredientRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngredientRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngredientRepository {
	mock := &IngredientRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
