// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// IngrtNomRepository is an autogenerated mock type for the IngrtNomRepository type
type IngrtNomRepository struct {
	mock.Mock
}

type IngrtNomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IngrtNomRepository) EXPECT() *IngrtNomRepository_Expecter {
	return &IngrtNomRepository_Expecter{mock: &_m.Mock}
}

// CreateIngredientNom provides a mock function with given fields: ctx, nomenclature
func (_m *IngrtNomRepository) CreateIngredientNom(ctx context.Context, nomenclature models.IngredientNomenclature) (models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, nomenclature)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredientNom")
	}

	var r0 models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)); ok {
		return rf(ctx, nomenclature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) models.IngredientNomenclature); ok {
		r0 = rf(ctx, nomenclature)
	} else {
		r0 = ret.Get(0).(models.IngredientNomenclature)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.IngredientNomenclature) error); ok {
		r1 = rf(ctx, nomenclature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngrtNomRepository_CreateIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredientNom'
type IngrtNomRepository_CreateIngredientNom_Call struct {
	*mock.Call
}

// CreateIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
//   - nomenclature models.IngredientNomenclature
func (_e *IngrtNomRepository_Expecter) CreateIngredientNom(ctx interface{}, nomenclature interface{}) *IngrtNomRepository_CreateIngredientNom_Call {
	return &IngrtNomRepository_CreateIngredientNom_Call{Call: _e.mock.On("CreateIngredientNom", ctx, nomenclature)}
}

func (_c *IngrtNomRepository_CreateIngredientNom_Call) Run(run func(ctx context.Context, nomenclature models.IngredientNomenclature)) *IngrtNomRepository_CreateIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.IngredientNomenclature))
	})
	return _c
}

func (_c *IngrtNomRepository_CreateIngredientNom_Call) Return(_a0 models.IngredientNomenclature, _a1 error) *IngrtNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngrtNomRepository_CreateIngredientNom_Call) RunAndReturn(run func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)) *IngrtNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// IsIngredientNomExistAndApproved provides a mock function with given fields: ctx, name
func (_m *IngrtNomRepository) IsIngredientNomExistAndApproved(ctx context.Context, name string) (bool, models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsIngredientNomExistAndApproved")
	}

	var r0 bool
	var r1 models.IngredientNomenclature
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, models.IngredientNomenclature, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) models.IngredientNomenclature); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(models.IngredientNomenclature)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IngrtNomRepository_IsIngredientNomExistAndApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsIngredientNomExistAndApproved'
type IngrtNomRepository_IsIngredientNomExistAndApproved_Call struct {
	*mock.Call
}

// IsIngredientNomExistAndApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *IngrtNomRepository_Expecter) IsIngredientNomExistAndApproved(ctx interface{}, name interface{}) *IngrtNomRepository_IsIngredientNomExistAndApproved_Call {
	return &IngrtNomRepository_IsIngredientNomExistAndApproved_Call{Call: _e.mock.On("IsIngredientNomExistAndApproved", ctx, name)}
}

func (_c *IngrtNomRepository_IsIngredientNomExistAndApproved_Call) Run(run func(ctx context.Context, name string)) *IngrtNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IngrtNomRepository_IsIngredientNomExistAndApproved_Call) Return(_a0 bool, _a1 models.IngredientNomenclature, _a2 error) *IngrtNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IngrtNomRepository_IsIngredientNomExistAndApproved_Call) RunAndReturn(run func(context.Context, string) (bool, models.IngredientNomenclature, error)) *IngrtNomRepository_IsIngredientNomExistAndApproved_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngrtNomRepository creates a new instance of IngrtNomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngrtNomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngrtNomRepository {
	mock := &IngrtNomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
