// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// IngredientNomRepository is an autogenerated mock type for the IngredientNomRepository type
type IngredientNomRepository struct {
	mock.Mock
}

type IngredientNomRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IngredientNomRepository) EXPECT() *IngredientNomRepository_Expecter {
	return &IngredientNomRepository_Expecter{mock: &_m.Mock}
}

// CreateIngredientNom provides a mock function with given fields: ctx, nomenclature
func (_m *IngredientNomRepository) CreateIngredientNom(ctx context.Context, nomenclature models.IngredientNomenclature) (models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, nomenclature)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngredientNom")
	}

	var r0 models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)); ok {
		return rf(ctx, nomenclature)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.IngredientNomenclature) models.IngredientNomenclature); ok {
		r0 = rf(ctx, nomenclature)
	} else {
		r0 = ret.Get(0).(models.IngredientNomenclature)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.IngredientNomenclature) error); ok {
		r1 = rf(ctx, nomenclature)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientNomRepository_CreateIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngredientNom'
type IngredientNomRepository_CreateIngredientNom_Call struct {
	*mock.Call
}

// CreateIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
//   - nomenclature models.IngredientNomenclature
func (_e *IngredientNomRepository_Expecter) CreateIngredientNom(ctx interface{}, nomenclature interface{}) *IngredientNomRepository_CreateIngredientNom_Call {
	return &IngredientNomRepository_CreateIngredientNom_Call{Call: _e.mock.On("CreateIngredientNom", ctx, nomenclature)}
}

func (_c *IngredientNomRepository_CreateIngredientNom_Call) Run(run func(ctx context.Context, nomenclature models.IngredientNomenclature)) *IngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.IngredientNomenclature))
	})
	return _c
}

func (_c *IngredientNomRepository_CreateIngredientNom_Call) Return(_a0 models.IngredientNomenclature, _a1 error) *IngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientNomRepository_CreateIngredientNom_Call) RunAndReturn(run func(context.Context, models.IngredientNomenclature) (models.IngredientNomenclature, error)) *IngredientNomRepository_CreateIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIngredientNom provides a mock function with given fields: ctx, id
func (_m *IngredientNomRepository) DeleteIngredientNom(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIngredientNom")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngredientNomRepository_DeleteIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIngredientNom'
type IngredientNomRepository_DeleteIngredientNom_Call struct {
	*mock.Call
}

// DeleteIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *IngredientNomRepository_Expecter) DeleteIngredientNom(ctx interface{}, id interface{}) *IngredientNomRepository_DeleteIngredientNom_Call {
	return &IngredientNomRepository_DeleteIngredientNom_Call{Call: _e.mock.On("DeleteIngredientNom", ctx, id)}
}

func (_c *IngredientNomRepository_DeleteIngredientNom_Call) Run(run func(ctx context.Context, id string)) *IngredientNomRepository_DeleteIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IngredientNomRepository_DeleteIngredientNom_Call) Return(_a0 error) *IngredientNomRepository_DeleteIngredientNom_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngredientNomRepository_DeleteIngredientNom_Call) RunAndReturn(run func(context.Context, string) error) *IngredientNomRepository_DeleteIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// GetApprovedIngredientNom provides a mock function with given fields: ctx
func (_m *IngredientNomRepository) GetApprovedIngredientNom(ctx context.Context) ([]models.IngredientNomenclature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApprovedIngredientNom")
	}

	var r0 []models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.IngredientNomenclature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.IngredientNomenclature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IngredientNomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientNomRepository_GetApprovedIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApprovedIngredientNom'
type IngredientNomRepository_GetApprovedIngredientNom_Call struct {
	*mock.Call
}

// GetApprovedIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IngredientNomRepository_Expecter) GetApprovedIngredientNom(ctx interface{}) *IngredientNomRepository_GetApprovedIngredientNom_Call {
	return &IngredientNomRepository_GetApprovedIngredientNom_Call{Call: _e.mock.On("GetApprovedIngredientNom", ctx)}
}

func (_c *IngredientNomRepository_GetApprovedIngredientNom_Call) Run(run func(ctx context.Context)) *IngredientNomRepository_GetApprovedIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IngredientNomRepository_GetApprovedIngredientNom_Call) Return(_a0 []models.IngredientNomenclature, _a1 error) *IngredientNomRepository_GetApprovedIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientNomRepository_GetApprovedIngredientNom_Call) RunAndReturn(run func(context.Context) ([]models.IngredientNomenclature, error)) *IngredientNomRepository_GetApprovedIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngredientNoms provides a mock function with given fields: ctx
func (_m *IngredientNomRepository) GetIngredientNoms(ctx context.Context) ([]models.IngredientNomenclature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetIngredientNoms")
	}

	var r0 []models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.IngredientNomenclature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.IngredientNomenclature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IngredientNomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientNomRepository_GetIngredientNoms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngredientNoms'
type IngredientNomRepository_GetIngredientNoms_Call struct {
	*mock.Call
}

// GetIngredientNoms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IngredientNomRepository_Expecter) GetIngredientNoms(ctx interface{}) *IngredientNomRepository_GetIngredientNoms_Call {
	return &IngredientNomRepository_GetIngredientNoms_Call{Call: _e.mock.On("GetIngredientNoms", ctx)}
}

func (_c *IngredientNomRepository_GetIngredientNoms_Call) Run(run func(ctx context.Context)) *IngredientNomRepository_GetIngredientNoms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IngredientNomRepository_GetIngredientNoms_Call) Return(_a0 []models.IngredientNomenclature, _a1 error) *IngredientNomRepository_GetIngredientNoms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientNomRepository_GetIngredientNoms_Call) RunAndReturn(run func(context.Context) ([]models.IngredientNomenclature, error)) *IngredientNomRepository_GetIngredientNoms_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalIngredientNom provides a mock function with given fields: ctx, userId
func (_m *IngredientNomRepository) GetPersonalIngredientNom(ctx context.Context, userId string) ([]models.IngredientNomenclature, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalIngredientNom")
	}

	var r0 []models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.IngredientNomenclature, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.IngredientNomenclature); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IngredientNomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientNomRepository_GetPersonalIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalIngredientNom'
type IngredientNomRepository_GetPersonalIngredientNom_Call struct {
	*mock.Call
}

// GetPersonalIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *IngredientNomRepository_Expecter) GetPersonalIngredientNom(ctx interface{}, userId interface{}) *IngredientNomRepository_GetPersonalIngredientNom_Call {
	return &IngredientNomRepository_GetPersonalIngredientNom_Call{Call: _e.mock.On("GetPersonalIngredientNom", ctx, userId)}
}

func (_c *IngredientNomRepository_GetPersonalIngredientNom_Call) Run(run func(ctx context.Context, userId string)) *IngredientNomRepository_GetPersonalIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IngredientNomRepository_GetPersonalIngredientNom_Call) Return(_a0 []models.IngredientNomenclature, _a1 error) *IngredientNomRepository_GetPersonalIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientNomRepository_GetPersonalIngredientNom_Call) RunAndReturn(run func(context.Context, string) ([]models.IngredientNomenclature, error)) *IngredientNomRepository_GetPersonalIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnapprovedIngredientNom provides a mock function with given fields: ctx
func (_m *IngredientNomRepository) GetUnapprovedIngredientNom(ctx context.Context) ([]models.IngredientNomenclature, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnapprovedIngredientNom")
	}

	var r0 []models.IngredientNomenclature
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.IngredientNomenclature, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.IngredientNomenclature); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.IngredientNomenclature)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IngredientNomRepository_GetUnapprovedIngredientNom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnapprovedIngredientNom'
type IngredientNomRepository_GetUnapprovedIngredientNom_Call struct {
	*mock.Call
}

// GetUnapprovedIngredientNom is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IngredientNomRepository_Expecter) GetUnapprovedIngredientNom(ctx interface{}) *IngredientNomRepository_GetUnapprovedIngredientNom_Call {
	return &IngredientNomRepository_GetUnapprovedIngredientNom_Call{Call: _e.mock.On("GetUnapprovedIngredientNom", ctx)}
}

func (_c *IngredientNomRepository_GetUnapprovedIngredientNom_Call) Run(run func(ctx context.Context)) *IngredientNomRepository_GetUnapprovedIngredientNom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IngredientNomRepository_GetUnapprovedIngredientNom_Call) Return(_a0 []models.IngredientNomenclature, _a1 error) *IngredientNomRepository_GetUnapprovedIngredientNom_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IngredientNomRepository_GetUnapprovedIngredientNom_Call) RunAndReturn(run func(context.Context) ([]models.IngredientNomenclature, error)) *IngredientNomRepository_GetUnapprovedIngredientNom_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngredientNomsApprovedStatus provides a mock function with given fields: ctx, nomenclatures
func (_m *IngredientNomRepository) UpdateIngredientNomsApprovedStatus(ctx context.Context, nomenclatures []models.IngredientNomenclature) error {
	ret := _m.Called(ctx, nomenclatures)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngredientNomsApprovedStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.IngredientNomenclature) error); ok {
		r0 = rf(ctx, nomenclatures)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngredientNomsApprovedStatus'
type IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call struct {
	*mock.Call
}

// UpdateIngredientNomsApprovedStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - nomenclatures []models.IngredientNomenclature
func (_e *IngredientNomRepository_Expecter) UpdateIngredientNomsApprovedStatus(ctx interface{}, nomenclatures interface{}) *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call {
	return &IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call{Call: _e.mock.On("UpdateIngredientNomsApprovedStatus", ctx, nomenclatures)}
}

func (_c *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call) Run(run func(ctx context.Context, nomenclatures []models.IngredientNomenclature)) *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.IngredientNomenclature))
	})
	return _c
}

func (_c *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call) Return(_a0 error) *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call) RunAndReturn(run func(context.Context, []models.IngredientNomenclature) error) *IngredientNomRepository_UpdateIngredientNomsApprovedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewIngredientNomRepository creates a new instance of IngredientNomRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIngredientNomRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IngredientNomRepository {
	mock := &IngredientNomRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
