// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// TagRepository is an autogenerated mock type for the TagRepository type
type TagRepository struct {
	mock.Mock
}

type TagRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TagRepository) EXPECT() *TagRepository_Expecter {
	return &TagRepository_Expecter{mock: &_m.Mock}
}

// CreateTag provides a mock function with given fields: ctx, tag
func (_m *TagRepository) CreateTag(ctx context.Context, tag models.Tag) (models.Tag, error) {
	ret := _m.Called(ctx, tag)

	if len(ret) == 0 {
		panic("no return value specified for CreateTag")
	}

	var r0 models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.Tag) (models.Tag, error)); ok {
		return rf(ctx, tag)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.Tag) models.Tag); ok {
		r0 = rf(ctx, tag)
	} else {
		r0 = ret.Get(0).(models.Tag)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.Tag) error); ok {
		r1 = rf(ctx, tag)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_CreateTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTag'
type TagRepository_CreateTag_Call struct {
	*mock.Call
}

// CreateTag is a helper method to define mock.On call
//   - ctx context.Context
//   - tag models.Tag
func (_e *TagRepository_Expecter) CreateTag(ctx interface{}, tag interface{}) *TagRepository_CreateTag_Call {
	return &TagRepository_CreateTag_Call{Call: _e.mock.On("CreateTag", ctx, tag)}
}

func (_c *TagRepository_CreateTag_Call) Run(run func(ctx context.Context, tag models.Tag)) *TagRepository_CreateTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.Tag))
	})
	return _c
}

func (_c *TagRepository_CreateTag_Call) Return(_a0 models.Tag, _a1 error) *TagRepository_CreateTag_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_CreateTag_Call) RunAndReturn(run func(context.Context, models.Tag) (models.Tag, error)) *TagRepository_CreateTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCocktailTag provides a mock function with given fields: ctx, cocktailId, tagId, userId, userRole
func (_m *TagRepository) DeleteCocktailTag(ctx context.Context, cocktailId string, tagId string, userId string, userRole int) error {
	ret := _m.Called(ctx, cocktailId, tagId, userId, userRole)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCocktailTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int) error); ok {
		r0 = rf(ctx, cocktailId, tagId, userId, userRole)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_DeleteCocktailTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCocktailTag'
type TagRepository_DeleteCocktailTag_Call struct {
	*mock.Call
}

// DeleteCocktailTag is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
//   - tagId string
//   - userId string
//   - userRole int
func (_e *TagRepository_Expecter) DeleteCocktailTag(ctx interface{}, cocktailId interface{}, tagId interface{}, userId interface{}, userRole interface{}) *TagRepository_DeleteCocktailTag_Call {
	return &TagRepository_DeleteCocktailTag_Call{Call: _e.mock.On("DeleteCocktailTag", ctx, cocktailId, tagId, userId, userRole)}
}

func (_c *TagRepository_DeleteCocktailTag_Call) Run(run func(ctx context.Context, cocktailId string, tagId string, userId string, userRole int)) *TagRepository_DeleteCocktailTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *TagRepository_DeleteCocktailTag_Call) Return(_a0 error) *TagRepository_DeleteCocktailTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_DeleteCocktailTag_Call) RunAndReturn(run func(context.Context, string, string, string, int) error) *TagRepository_DeleteCocktailTag_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTag provides a mock function with given fields: ctx, id
func (_m *TagRepository) DeleteTag(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_DeleteTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTag'
type TagRepository_DeleteTag_Call struct {
	*mock.Call
}

// DeleteTag is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *TagRepository_Expecter) DeleteTag(ctx interface{}, id interface{}) *TagRepository_DeleteTag_Call {
	return &TagRepository_DeleteTag_Call{Call: _e.mock.On("DeleteTag", ctx, id)}
}

func (_c *TagRepository_DeleteTag_Call) Run(run func(ctx context.Context, id string)) *TagRepository_DeleteTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TagRepository_DeleteTag_Call) Return(_a0 error) *TagRepository_DeleteTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_DeleteTag_Call) RunAndReturn(run func(context.Context, string) error) *TagRepository_DeleteTag_Call {
	_c.Call.Return(run)
	return _c
}

// GetPersonalTags provides a mock function with given fields: ctx, userId
func (_m *TagRepository) GetPersonalTags(ctx context.Context, userId string) ([]models.Tag, error) {
	ret := _m.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetPersonalTags")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Tag, error)); ok {
		return rf(ctx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Tag); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_GetPersonalTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPersonalTags'
type TagRepository_GetPersonalTags_Call struct {
	*mock.Call
}

// GetPersonalTags is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *TagRepository_Expecter) GetPersonalTags(ctx interface{}, userId interface{}) *TagRepository_GetPersonalTags_Call {
	return &TagRepository_GetPersonalTags_Call{Call: _e.mock.On("GetPersonalTags", ctx, userId)}
}

func (_c *TagRepository_GetPersonalTags_Call) Run(run func(ctx context.Context, userId string)) *TagRepository_GetPersonalTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TagRepository_GetPersonalTags_Call) Return(_a0 []models.Tag, _a1 error) *TagRepository_GetPersonalTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_GetPersonalTags_Call) RunAndReturn(run func(context.Context, string) ([]models.Tag, error)) *TagRepository_GetPersonalTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetTagsByCocktailID provides a mock function with given fields: ctx, cocktailId
func (_m *TagRepository) GetTagsByCocktailID(ctx context.Context, cocktailId string) ([]models.Tag, error) {
	ret := _m.Called(ctx, cocktailId)

	if len(ret) == 0 {
		panic("no return value specified for GetTagsByCocktailID")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Tag, error)); ok {
		return rf(ctx, cocktailId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Tag); ok {
		r0 = rf(ctx, cocktailId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cocktailId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_GetTagsByCocktailID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTagsByCocktailID'
type TagRepository_GetTagsByCocktailID_Call struct {
	*mock.Call
}

// GetTagsByCocktailID is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
func (_e *TagRepository_Expecter) GetTagsByCocktailID(ctx interface{}, cocktailId interface{}) *TagRepository_GetTagsByCocktailID_Call {
	return &TagRepository_GetTagsByCocktailID_Call{Call: _e.mock.On("GetTagsByCocktailID", ctx, cocktailId)}
}

func (_c *TagRepository_GetTagsByCocktailID_Call) Run(run func(ctx context.Context, cocktailId string)) *TagRepository_GetTagsByCocktailID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TagRepository_GetTagsByCocktailID_Call) Return(_a0 []models.Tag, _a1 error) *TagRepository_GetTagsByCocktailID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_GetTagsByCocktailID_Call) RunAndReturn(run func(context.Context, string) ([]models.Tag, error)) *TagRepository_GetTagsByCocktailID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnapprovedTags provides a mock function with given fields: ctx
func (_m *TagRepository) GetUnapprovedTags(ctx context.Context) ([]models.Tag, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnapprovedTags")
	}

	var r0 []models.Tag
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]models.Tag, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []models.Tag); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Tag)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TagRepository_GetUnapprovedTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnapprovedTags'
type TagRepository_GetUnapprovedTags_Call struct {
	*mock.Call
}

// GetUnapprovedTags is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TagRepository_Expecter) GetUnapprovedTags(ctx interface{}) *TagRepository_GetUnapprovedTags_Call {
	return &TagRepository_GetUnapprovedTags_Call{Call: _e.mock.On("GetUnapprovedTags", ctx)}
}

func (_c *TagRepository_GetUnapprovedTags_Call) Run(run func(ctx context.Context)) *TagRepository_GetUnapprovedTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TagRepository_GetUnapprovedTags_Call) Return(_a0 []models.Tag, _a1 error) *TagRepository_GetUnapprovedTags_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TagRepository_GetUnapprovedTags_Call) RunAndReturn(run func(context.Context) ([]models.Tag, error)) *TagRepository_GetUnapprovedTags_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCocktailTag provides a mock function with given fields: ctx, cocktailId, tagId
func (_m *TagRepository) InsertCocktailTag(ctx context.Context, cocktailId string, tagId string) error {
	ret := _m.Called(ctx, cocktailId, tagId)

	if len(ret) == 0 {
		panic("no return value specified for InsertCocktailTag")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, cocktailId, tagId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_InsertCocktailTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCocktailTag'
type TagRepository_InsertCocktailTag_Call struct {
	*mock.Call
}

// InsertCocktailTag is a helper method to define mock.On call
//   - ctx context.Context
//   - cocktailId string
//   - tagId string
func (_e *TagRepository_Expecter) InsertCocktailTag(ctx interface{}, cocktailId interface{}, tagId interface{}) *TagRepository_InsertCocktailTag_Call {
	return &TagRepository_InsertCocktailTag_Call{Call: _e.mock.On("InsertCocktailTag", ctx, cocktailId, tagId)}
}

func (_c *TagRepository_InsertCocktailTag_Call) Run(run func(ctx context.Context, cocktailId string, tagId string)) *TagRepository_InsertCocktailTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *TagRepository_InsertCocktailTag_Call) Return(_a0 error) *TagRepository_InsertCocktailTag_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_InsertCocktailTag_Call) RunAndReturn(run func(context.Context, string, string) error) *TagRepository_InsertCocktailTag_Call {
	_c.Call.Return(run)
	return _c
}

// IsTagExistAndApproved provides a mock function with given fields: ctx, name
func (_m *TagRepository) IsTagExistAndApproved(ctx context.Context, name string) (bool, models.Tag, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for IsTagExistAndApproved")
	}

	var r0 bool
	var r1 models.Tag
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, models.Tag, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) models.Tag); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Get(1).(models.Tag)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, name)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// TagRepository_IsTagExistAndApproved_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTagExistAndApproved'
type TagRepository_IsTagExistAndApproved_Call struct {
	*mock.Call
}

// IsTagExistAndApproved is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *TagRepository_Expecter) IsTagExistAndApproved(ctx interface{}, name interface{}) *TagRepository_IsTagExistAndApproved_Call {
	return &TagRepository_IsTagExistAndApproved_Call{Call: _e.mock.On("IsTagExistAndApproved", ctx, name)}
}

func (_c *TagRepository_IsTagExistAndApproved_Call) Run(run func(ctx context.Context, name string)) *TagRepository_IsTagExistAndApproved_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *TagRepository_IsTagExistAndApproved_Call) Return(_a0 bool, _a1 models.Tag, _a2 error) *TagRepository_IsTagExistAndApproved_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *TagRepository_IsTagExistAndApproved_Call) RunAndReturn(run func(context.Context, string) (bool, models.Tag, error)) *TagRepository_IsTagExistAndApproved_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTagsApprovedStatus provides a mock function with given fields: ctx, tags
func (_m *TagRepository) UpdateTagsApprovedStatus(ctx context.Context, tags []models.Tag) error {
	ret := _m.Called(ctx, tags)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTagsApprovedStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Tag) error); ok {
		r0 = rf(ctx, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TagRepository_UpdateTagsApprovedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTagsApprovedStatus'
type TagRepository_UpdateTagsApprovedStatus_Call struct {
	*mock.Call
}

// UpdateTagsApprovedStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tags []models.Tag
func (_e *TagRepository_Expecter) UpdateTagsApprovedStatus(ctx interface{}, tags interface{}) *TagRepository_UpdateTagsApprovedStatus_Call {
	return &TagRepository_UpdateTagsApprovedStatus_Call{Call: _e.mock.On("UpdateTagsApprovedStatus", ctx, tags)}
}

func (_c *TagRepository_UpdateTagsApprovedStatus_Call) Run(run func(ctx context.Context, tags []models.Tag)) *TagRepository_UpdateTagsApprovedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Tag))
	})
	return _c
}

func (_c *TagRepository_UpdateTagsApprovedStatus_Call) Return(_a0 error) *TagRepository_UpdateTagsApprovedStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *TagRepository_UpdateTagsApprovedStatus_Call) RunAndReturn(run func(context.Context, []models.Tag) error) *TagRepository_UpdateTagsApprovedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewTagRepository creates a new instance of TagRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTagRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TagRepository {
	mock := &TagRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
