// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	models "nickbar_v2/internal/models/models"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function with given fields: nickname
func (_m *UserRepository) CreateUser(nickname string) (models.User, error) {
	ret := _m.Called(nickname)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(nickname)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(nickname)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - nickname string
func (_e *UserRepository_Expecter) CreateUser(nickname interface{}) *UserRepository_CreateUser_Call {
	return &UserRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", nickname)}
}

func (_c *UserRepository_CreateUser_Call) Run(run func(nickname string)) *UserRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_CreateUser_Call) Return(_a0 models.User, _a1 error) *UserRepository_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_CreateUser_Call) RunAndReturn(run func(string) (models.User, error)) *UserRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: nickname
func (_m *UserRepository) DeleteUser(nickname string) error {
	ret := _m.Called(nickname)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(nickname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - nickname string
func (_e *UserRepository_Expecter) DeleteUser(nickname interface{}) *UserRepository_DeleteUser_Call {
	return &UserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", nickname)}
}

func (_c *UserRepository_DeleteUser_Call) Run(run func(nickname string)) *UserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_DeleteUser_Call) Return(_a0 error) *UserRepository_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_DeleteUser_Call) RunAndReturn(run func(string) error) *UserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: nickname
func (_m *UserRepository) GetUser(nickname string) (models.User, error) {
	ret := _m.Called(nickname)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (models.User, error)); ok {
		return rf(nickname)
	}
	if rf, ok := ret.Get(0).(func(string) models.User); ok {
		r0 = rf(nickname)
	} else {
		r0 = ret.Get(0).(models.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nickname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - nickname string
func (_e *UserRepository_Expecter) GetUser(nickname interface{}) *UserRepository_GetUser_Call {
	return &UserRepository_GetUser_Call{Call: _e.mock.On("GetUser", nickname)}
}

func (_c *UserRepository_GetUser_Call) Run(run func(nickname string)) *UserRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *UserRepository_GetUser_Call) Return(_a0 models.User, _a1 error) *UserRepository_GetUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetUser_Call) RunAndReturn(run func(string) (models.User, error)) *UserRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserList provides a mock function with no fields
func (_m *UserRepository) GetUserList() ([]models.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUserList")
	}

	var r0 []models.User
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]models.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []models.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRepository_GetUserList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserList'
type UserRepository_GetUserList_Call struct {
	*mock.Call
}

// GetUserList is a helper method to define mock.On call
func (_e *UserRepository_Expecter) GetUserList() *UserRepository_GetUserList_Call {
	return &UserRepository_GetUserList_Call{Call: _e.mock.On("GetUserList")}
}

func (_c *UserRepository_GetUserList_Call) Run(run func()) *UserRepository_GetUserList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UserRepository_GetUserList_Call) Return(_a0 []models.User, _a1 error) *UserRepository_GetUserList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UserRepository_GetUserList_Call) RunAndReturn(run func() ([]models.User, error)) *UserRepository_GetUserList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePicture provides a mock function with given fields: user
func (_m *UserRepository) UpdatePicture(user models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePicture")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdatePicture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePicture'
type UserRepository_UpdatePicture_Call struct {
	*mock.Call
}

// UpdatePicture is a helper method to define mock.On call
//   - user models.User
func (_e *UserRepository_Expecter) UpdatePicture(user interface{}) *UserRepository_UpdatePicture_Call {
	return &UserRepository_UpdatePicture_Call{Call: _e.mock.On("UpdatePicture", user)}
}

func (_c *UserRepository_UpdatePicture_Call) Run(run func(user models.User)) *UserRepository_UpdatePicture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.User))
	})
	return _c
}

func (_c *UserRepository_UpdatePicture_Call) Return(_a0 error) *UserRepository_UpdatePicture_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdatePicture_Call) RunAndReturn(run func(models.User) error) *UserRepository_UpdatePicture_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: user
func (_m *UserRepository) UpdateRole(user models.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(models.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRepository_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type UserRepository_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - user models.User
func (_e *UserRepository_Expecter) UpdateRole(user interface{}) *UserRepository_UpdateRole_Call {
	return &UserRepository_UpdateRole_Call{Call: _e.mock.On("UpdateRole", user)}
}

func (_c *UserRepository_UpdateRole_Call) Run(run func(user models.User)) *UserRepository_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(models.User))
	})
	return _c
}

func (_c *UserRepository_UpdateRole_Call) Return(_a0 error) *UserRepository_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserRepository_UpdateRole_Call) RunAndReturn(run func(models.User) error) *UserRepository_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
